Add ability for users to customise their install
HighlineBETA/ptah pull request #1
Opened 2018-10-02 20:16 UTC by Haegin

2018-10-22 16:36 UTC, Haegin commented on profiles/dev/Brewfile
> +tap 'neovim/neovim'
kill this

2018-10-22 16:37 UTC, Haegin commented on profiles/dev/setup
> +  if [[ -e $HOME/.asdf ]]; then
need to install asdf first

2018-12-10 21:48 UTC, Haegin commented on profiles/dev/setup
> +  if [[ -e $HOME/.asdf ]]; then
It's installed already by default.

2018-12-10 21:50 UTC, 0xrohan10 requested changes
A couple things

2018-12-10 21:50 UTC, rohannair commented on profiles/dev/setup
> +install_lang "elixir"
Erlang needs to be installed.

2018-12-10 21:52 UTC, 0xrohan10 approved these changes

2018-12-10 21:53 UTC, merged